### ISSUE TITLE
GUI unresponsive

### ISSUE THREAD

**Issue by strangeoddity** [Matt529/CCAutotyper#1]
Opening GUI results in blank screen after initial info screen. Does work if run from command line.

Win 7 64 bit with Java 64 (no 32 bit java installed)

Log file when running gui:

15:20:08 - [CC Autotyper][INFO ]: 
15:20:08 - [CC Autotyper][INFO ]: ========== SYS INFO ==========
15:20:08 - [CC Autotyper][INFO ]: JAVA_HOME: C:\Program Files\Java\jre1.8.0_25
15:20:08 - [CC Autotyper][INFO ]: JAVA_VEND: Oracle Corporation
15:20:08 - [CC Autotyper][INFO ]: JAVA_VURL: http://java.oracle.com/
15:20:08 - [CC Autotyper][INFO ]: RUNNING Java 1.8.0_25 compiled to class version 52.0
15:20:08 - [CC Autotyper][INFO ]: USING Java HotSpot(TM) 64-Bit Server VM 25.25-b02 by Oracle Corporation w/ compiler null
15:20:08 - [CC Autotyper][INFO ]: OS: Windows 7 x64 6.1
15:20:08 - [CC Autotyper][INFO ]: CP: E:\cctyper\ccautotyper.jar
15:20:08 - [CC Autotyper][INFO ]: TN: 8 cores TMP_DIR: C:\Users\Simon\AppData\Local\Temp\
15:20:08 - [CC Autotyper][INFO ]: SPECIFIED Java Platform API Specification 1.8 by Oracle Corporation
15:20:08 - [CC Autotyper][INFO ]: SPECIFIED Java Virtual Machine Specification 1.8 by Oracle Corporation
15:20:08 - [CC Autotyper][INFO ]: ==============================
15:20:08 - [CC Autotyper][INFO ]: 
15:20:08 - [CC Autotyper][INFO ]: SUCCESS! LookAndFeel set to System LookAndFeel -- com.sun.java.swing.plaf.windows.WindowsLookAndFeel!
15:20:08 - [GUI  ][DEBUG]: Found Icon: icon32.png
15:20:08 - [GUI  ][DEBUG]: Found Icon: icon48.png
15:20:08 - [GUI  ][DEBUG]: Found Icon: icon64.png
15:20:08 - [GUI  ][DEBUG]: Found Icon: icon128.png
15:20:08 - [GUI  ][ERROR]: ===============EXCEPTION===============
15:20:08 - [GUI  ][ERROR]: Exception of type java.lang.NullPointerException caught!
15:20:08 - [GUI  ][ERROR]: Error Message: null
15:20:08 - [GUI  ][ERROR]: Caught by UncaughtExceptionHandler
15:20:08 - [GUI  ][ERROR]: =======================================
15:20:08 - [GUI  ][ERROR]: Stack Trace: 
15:20:08 - [GUI  ][ERROR]:    com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
15:20:08 - [GUI  ][ERROR]:      com.google.common.collect.Lists.newArrayList(Lists.java:142)
15:20:08 - [GUI  ][ERROR]:      com.mattc.autotyper.gui.AutotyperWindow.checkDefaultCompletions(AutotyperWindow.java:554)
15:20:08 - [GUI  ][ERROR]:      com.mattc.autotyper.gui.AutotyperWindow.init(AutotyperWindow.java:108)
15:20:08 - [GUI  ][ERROR]:      com.mattc.autotyper.gui.AutotyperWindow.access$1(AutotyperWindow.java:99)
15:20:08 - [GUI  ][ERROR]:      com.mattc.autotyper.gui.AutotyperWindow$1.run(AutotyperWindow.java:89)
15:20:08 - [GUI  ][ERROR]:      java.awt.event.InvocationEvent.dispatch(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventQueue.dispatchEventImpl(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventQueue.access$400(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventQueue$3.run(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventQueue$3.run(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.security.AccessController.doPrivileged(Native Method)
15:20:08 - [GUI  ][ERROR]:      java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventQueue.dispatchEvent(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.pumpEvents(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.pumpEvents(Unknown Source)
15:20:08 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.run(Unknown Source)
15:20:08 - [GUI  ][ERROR]: ===============EXCEPTION===============

from command line (works):

15:24:07 - [CC Autotyper][INFO ]: 
15:24:07 - [CC Autotyper][INFO ]: ========== SYS INFO ==========
15:24:07 - [CC Autotyper][INFO ]: JAVA_HOME: C:\Program Files\Java\jre1.8.0_25
15:24:07 - [CC Autotyper][INFO ]: JAVA_VEND: Oracle Corporation
15:24:07 - [CC Autotyper][INFO ]: JAVA_VURL: http://java.oracle.com/
15:24:07 - [CC Autotyper][INFO ]: RUNNING Java 1.8.0_25 compiled to class version 52.0
15:24:07 - [CC Autotyper][INFO ]: USING Java HotSpot(TM) 64-Bit Server VM 25.25-b02 by Oracle Corporation w/ compiler null
15:24:07 - [CC Autotyper][INFO ]: OS: Windows 7 x64 6.1
15:24:07 - [CC Autotyper][INFO ]: CP: ccautotyper.jar
15:24:07 - [CC Autotyper][INFO ]: TN: 8 cores TMP_DIR: C:\Users\Simon\AppData\Local\Temp\
15:24:07 - [CC Autotyper][INFO ]: SPECIFIED Java Platform API Specification 1.8 by Oracle Corporation
15:24:07 - [CC Autotyper][INFO ]: SPECIFIED Java Virtual Machine Specification 1.8 by Oracle Corporation
15:24:07 - [CC Autotyper][INFO ]: ==============================
15:24:07 - [CC Autotyper][INFO ]: 
15:24:07 - [CC Autotyper][INFO ]: SUCCESS! LookAndFeel set to System LookAndFeel -- com.sun.java.swing.plaf.windows.WindowsLookAndFeel!
15:24:07 - [GUI  ][DEBUG]: Found Icon: icon32.png
15:24:07 - [CC Autotyper][INFO ]: Received Arguments: [paste, p4zeq7Ma, -wait, 5, -inDelay, 10]
15:24:07 - [CC Autotyper][INFO ]: Downloading p4zeq7Ma from http://www.pastebin.com/raw.php?i=p4zeq7Ma...
15:24:07 - [GUI  ][DEBUG]: Found Icon: icon48.png
15:24:07 - [GUI  ][DEBUG]: Found Icon: icon64.png
15:24:07 - [GUI  ][DEBUG]: Found Icon: icon128.png
15:24:07 - [GUI  ][ERROR]: ===============EXCEPTION===============
15:24:07 - [GUI  ][ERROR]: Exception of type java.lang.NullPointerException caught!
15:24:07 - [GUI  ][ERROR]: Error Message: null
15:24:07 - [GUI  ][ERROR]: Caught by UncaughtExceptionHandler
15:24:07 - [GUI  ][ERROR]: =======================================
15:24:07 - [GUI  ][ERROR]: Stack Trace: 
15:24:07 - [GUI  ][ERROR]:    com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
15:24:07 - [GUI  ][ERROR]:      com.google.common.collect.Lists.newArrayList(Lists.java:142)
15:24:07 - [GUI  ][ERROR]:      com.mattc.autotyper.gui.AutotyperWindow.checkDefaultCompletions(AutotyperWindow.java:554)
15:24:07 - [GUI  ][ERROR]:      com.mattc.autotyper.gui.AutotyperWindow.init(AutotyperWindow.java:108)
15:24:07 - [GUI  ][ERROR]:      com.mattc.autotyper.gui.AutotyperWindow.access$1(AutotyperWindow.java:99)
15:24:07 - [GUI  ][ERROR]:      com.mattc.autotyper.gui.AutotyperWindow$1.run(AutotyperWindow.java:89)
15:24:07 - [GUI  ][ERROR]:      java.awt.event.InvocationEvent.dispatch(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventQueue.dispatchEventImpl(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventQueue.access$400(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventQueue$3.run(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventQueue$3.run(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.security.AccessController.doPrivileged(Native Method)
15:24:07 - [GUI  ][ERROR]:      java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventQueue.dispatchEvent(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.pumpEvents(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.pumpEvents(Unknown Source)
15:24:07 - [GUI  ][ERROR]:      java.awt.EventDispatchThread.run(Unknown Source)
15:24:07 - [GUI  ][ERROR]: ===============EXCEPTION===============
15:24:08 - [CC Autotyper][INFO ]: Finished!
15:24:08 - [CC Autotyper][DEBUG]: WaitTime set to 5000 milliseconds
15:24:08 - [CC Autotyper][DEBUG]: InputDelay set to 10 milliseconds
15:24:13 - [CC Autotyper][INFO ]: Writing File of Size 4 KB consisting of 168 lines
15:26:19 - [CC Autotyper][DEBUG]: FINISHED
15:26:19 - [Shutdown][DEBUG]: Finalizing Registers...

**Comment by glossawy** [comment]
Ah, I realize the problem that was not possible in my dev environment. It uses the Windows Registry (or some equivalent on Unix) to store your history of locations. Just as a credit to the programs I used to test, I give them short descriptions. The code for that gratuity does not account for Nulls and Guava will not allow nulls. 

I just need to re-arrange a few lines and do a check for nulls and it should be fixed.

**Note: This will not occur in the upcoming JavaFX GUI which uses custom Auto-Completion as opposed to an Auto-Completion library and these checks are unnecessary. This will be fixed to account for the rare case where JavaFX is not available.**

**Comment by strangeoddity** [comment]
Aha - I'll pretend I understand what you're saying!

Using cctyper right now to load a big reactors program - very cool

thanks for your work.

simonA

On 8 January 2015 at 17:15, Matthew notifications@github.com wrote:

> Ah, I realize the problem that was not possible in my dev environment. It
> uses the Windows Registry (or some equivalent on Unix) to store your
> history of locations. Just as a credit to the programs I used to test, I
> give them short descriptions. The the code for that gratuity does not
> account for Nulls and Guava will not allow nulls.
> 
> I just need to re-arrange a few lines and do a check for nulls and it
> should be fixed.
> 
> _Note: This will not occur in the upcoming JavaFX GUI which uses custom
> Auto-Completion as opposed to a Auto Completion library and these checks
> are unnecessary. This will be fixed to account for the rare case where
> JavaFX is not available._
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Matt529/CCAutotyper/issues/1#issuecomment-69213217.

## 

Simon Appleton
http://www.google.com/profiles/simonappleton
simonappleton@gmail.com
simon@digitaljourneyman.com

**Comment by glossawy** [comment]
Resolved in v2.0a via new JavaFX GUI. Also resolved in Swing Branch.
