### ISSUE TITLE
Add pause functionality?

### ISSUE THREAD

**Issue by strangeoddity** [Matt529/CCAutotyper#2]
This may be in the gui version, am using command line.

My server kicks after 30 mins 'idling', which was triggered during input. A pause and resume would be useful to avoid this...

s

**Comment by glossawy** [comment]
Aha, another bug. Thanks for reporting them. Haven't had a proper test environment besides a SIngle Player CC only world and I didn't test pause functionality on Command Line. It is intended and with the new implementation that will be released tonight it will work properly. 

Await v2.0, unfortunately I have no alternative for you at this time. How large is this file?

**Comment by strangeoddity** [comment]
1000 lines... it occurs to me I simply need to separate the file into a few
chunks and load them one at a time...

s

On 9 January 2015 at 01:48, Matthew notifications@github.com wrote:

> Aha, another bug. Thanks for reporting them. Haven't had a proper test
> environment besides a SIngle Player CC only world and I didn't test pause
> functionality on Command Line. It is intended and with the new
> implementation that will be released tonight it will work properly.
> 
> Await v2.0, unfortunately I have no alternative for you at this time. How
> large is this file?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Matt529/CCAutotyper/issues/2#issuecomment-69282130.

## 

Simon Appleton
http://www.google.com/profiles/simonappleton
simonappleton@gmail.com
simon@digitaljourneyman.com

**Comment by glossawy** [comment]
Resolved in v2.0a
