### ISSUE TITLE
Launch gui etc, approve, say yes, nothing happens...

### ISSUE THREAD

**Issue by strangeoddity** [Matt529/CCAutotyper#3]
tested to minecraft and to note pad. gui works fine (though do/d not confirm doesn't seem to have any effect?), but once I approve and hit yes, no typing.

14:11:22 - [CC Autotyper][INFO ]: 
14:11:22 - [CC Autotyper][INFO ]: ========== SYS INFO ==========
14:11:22 - [CC Autotyper][INFO ]: JAVA_HOME: E:\cctyper\jre
14:11:22 - [CC Autotyper][INFO ]: JAVA_VEND: Oracle Corporation
14:11:22 - [CC Autotyper][INFO ]: JAVA_VURL: http://java.oracle.com/
14:11:22 - [CC Autotyper][INFO ]: RUNNING Java 1.8.0_25 compiled to class version 52.0
14:11:22 - [CC Autotyper][INFO ]: USING Java HotSpot(TM) 64-Bit Server VM 25.25-b02 by Oracle Corporation w/ compiler null
14:11:22 - [CC Autotyper][INFO ]: OS: Windows 7 x64 6.1
14:11:22 - [CC Autotyper][INFO ]: CP: E:\cctyper\ccautotyper.jar
14:11:22 - [CC Autotyper][INFO ]: TN: 8 cores TMP_DIR: C:\Users\Simon\AppData\Local\Temp\
14:11:22 - [CC Autotyper][INFO ]: SPECIFIED Java Platform API Specification 1.8 by Oracle Corporation
14:11:22 - [CC Autotyper][INFO ]: SPECIFIED Java Virtual Machine Specification 1.8 by Oracle Corporation
14:11:22 - [CC Autotyper][INFO ]: ==============================
14:11:22 - [CC Autotyper][INFO ]: 
14:11:23 - [CC Autotyper][INFO ]: SUCCESS! LookAndFeel set to System LookAndFeel -- com.sun.java.swing.plaf.windows.WindowsLookAndFeel!
14:11:23 - [CC Autotyper][DEBUG]: Using JavaFX GUI
14:11:25 - [FX_GUI][INFO ]: Add FXParseable com.mattc.autotyper.gui.fx.AutoCompleteTextField as %at
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-coffeescript for 'CoffeeScript'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-lua for 'Lua'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-properties for 'Properties'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-csharp for 'CSharp'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-ini for 'INI'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-sql for 'SQL'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-c++src for 'C++'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-javascript for 'JavaScript'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-erlang for 'Erlang'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-yaml for 'YAML'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-css for 'CSS'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-csrc for 'C'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-pascal for 'Pascal'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-rust for 'Rust'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-objectivec for 'Objective-C'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-ruby for 'Ruby'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-html for 'HTML'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-hive for 'HIVE'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-mssql for 'MsSQL'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-mariadb for 'MariaDB'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-scala for 'Scala'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode application/sparql-query for 'SparQL'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-r for 'R'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-markdown for 'Markdown'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-common-lisp for 'Common Lisp'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-shell for 'Shell'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-haskell for 'Haskell'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-hxml for 'Haxe'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-perl for 'Perl'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-python for 'Python'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/vbscript for 'VBScript'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-groovy for 'Groovy'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-tcl for 'Tcl'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-php for 'PHP'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-cassandra for 'CassandraQL'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-go for 'Go'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-django for 'Django'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-fortran for 'FORTRAN'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-spreadsheet for 'Spreadsheet'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/xml for 'XML'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-cobol for 'COBOL'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-java for 'Java'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-vb for 'Visual BASIC'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-stsrc for 'SmallTalk'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-mysql for 'MySQL'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-octave for 'Octave'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-apl for 'APL'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-plsql for 'plSQL'...
14:11:25 - [FX_GUI][INFO ]: Installed Mode text/x-clojure for 'Clojure'...
14:11:25 - [FX_GUI][DEBUG]: Found icon32.png
14:11:25 - [FX_GUI][DEBUG]: Found icon48.png
14:11:25 - [FX_GUI][DEBUG]: Found icon64.png
14:11:25 - [FX_GUI][DEBUG]: Found icon128.png
14:11:36 - [FX_GUI][INFO ]: Downloading AWbyyx5E from http://www.pastebin.com/raw.php?i=AWbyyx5E...
14:11:36 - [FX_GUI][INFO ]: Finished!
14:11:53 - [Typer][INFO ]: Writing File of Size 15 KB consisting of 519 lines
14:11:53 - [Typer][ERROR]: ===============EXCEPTION===============
14:11:53 - [Typer][ERROR]: Exception of type java.lang.IllegalStateException caught!
14:11:53 - [Typer][ERROR]: Error Message: This operation is permitted on the event thread only; currentThread = Typer
14:11:53 - [Typer][ERROR]: Caught by UncaughtExceptionHandler
14:11:53 - [Typer][ERROR]: =======================================
14:11:53 - [Typer][ERROR]: Stack Trace: 
14:11:53 - [Typer][ERROR]:    com.sun.glass.ui.Application.checkEventThread(Application.java:445)
14:11:53 - [Typer][ERROR]:      com.sun.glass.ui.Robot.keyPress(Robot.java:68)
14:11:53 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.doType(FXKeyboard.java:590)
14:11:53 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.doType(FXKeyboard.java:577)
14:11:53 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.type(FXKeyboard.java:190)
14:11:53 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.typeFile(FXKeyboard.java:461)
14:11:53 - [Typer][ERROR]:      com.mattc.autotyper.gui.fx.FXAutotyperWindow$5$2.run(FXAutotyperWindow.java:254)
14:11:53 - [Typer][ERROR]:      java.lang.Thread.run(Thread.java:745)
14:11:53 - [Typer][ERROR]: ===============EXCEPTION===============
14:12:10 - [FX_GUI][INFO ]: Downloading AWbyyx5E from http://www.pastebin.com/raw.php?i=AWbyyx5E...
14:12:10 - [FX_GUI][INFO ]: Finished!
14:12:22 - [Typer][INFO ]: Writing File of Size 15 KB consisting of 519 lines
14:12:22 - [Typer][ERROR]: ===============EXCEPTION===============
14:12:22 - [Typer][ERROR]: Exception of type java.lang.IllegalStateException caught!
14:12:22 - [Typer][ERROR]: Error Message: This operation is permitted on the event thread only; currentThread = Typer
14:12:22 - [Typer][ERROR]: Caught by UncaughtExceptionHandler
14:12:22 - [Typer][ERROR]: =======================================
14:12:22 - [Typer][ERROR]: Stack Trace: 
14:12:22 - [Typer][ERROR]:    com.sun.glass.ui.Application.checkEventThread(Application.java:445)
14:12:22 - [Typer][ERROR]:      com.sun.glass.ui.Robot.keyPress(Robot.java:68)
14:12:22 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.doType(FXKeyboard.java:590)
14:12:22 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.doType(FXKeyboard.java:577)
14:12:22 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.type(FXKeyboard.java:190)
14:12:22 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.typeFile(FXKeyboard.java:461)
14:12:22 - [Typer][ERROR]:      com.mattc.autotyper.gui.fx.FXAutotyperWindow$5$2.run(FXAutotyperWindow.java:254)
14:12:22 - [Typer][ERROR]:      java.lang.Thread.run(Thread.java:745)
14:12:22 - [Typer][ERROR]: ===============EXCEPTION===============
14:13:00 - [FX_GUI][INFO ]: Downloading AWbyyx5E from http://www.pastebin.com/raw.php?i=AWbyyx5E...
14:13:01 - [FX_GUI][INFO ]: Finished!
14:13:10 - [Typer][INFO ]: Writing File of Size 15 KB consisting of 519 lines
14:13:10 - [Typer][ERROR]: ===============EXCEPTION===============
14:13:10 - [Typer][ERROR]: Exception of type java.lang.IllegalStateException caught!
14:13:10 - [Typer][ERROR]: Error Message: This operation is permitted on the event thread only; currentThread = Typer
14:13:10 - [Typer][ERROR]: Caught by UncaughtExceptionHandler
14:13:10 - [Typer][ERROR]: =======================================
14:13:10 - [Typer][ERROR]: Stack Trace: 
14:13:10 - [Typer][ERROR]:    com.sun.glass.ui.Application.checkEventThread(Application.java:445)
14:13:10 - [Typer][ERROR]:      com.sun.glass.ui.Robot.keyPress(Robot.java:68)
14:13:10 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.doType(FXKeyboard.java:590)
14:13:10 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.doType(FXKeyboard.java:577)
14:13:10 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.type(FXKeyboard.java:190)
14:13:10 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.typeFile(FXKeyboard.java:461)
14:13:10 - [Typer][ERROR]:      com.mattc.autotyper.gui.fx.FXAutotyperWindow$5$2.run(FXAutotyperWindow.java:254)
14:13:10 - [Typer][ERROR]:      java.lang.Thread.run(Thread.java:745)
14:13:10 - [Typer][ERROR]: ===============EXCEPTION===============
14:13:25 - [FX_GUI][INFO ]: Downloading AWbyyx5E from http://www.pastebin.com/raw.php?i=AWbyyx5E...
14:13:25 - [FX_GUI][INFO ]: Finished!
14:13:35 - [Typer][INFO ]: Writing File of Size 15 KB consisting of 519 lines
14:13:35 - [Typer][ERROR]: ===============EXCEPTION===============
14:13:35 - [Typer][ERROR]: Exception of type java.lang.IllegalStateException caught!
14:13:35 - [Typer][ERROR]: Error Message: This operation is permitted on the event thread only; currentThread = Typer
14:13:35 - [Typer][ERROR]: Caught by UncaughtExceptionHandler
14:13:35 - [Typer][ERROR]: =======================================
14:13:35 - [Typer][ERROR]: Stack Trace: 
14:13:35 - [Typer][ERROR]:    com.sun.glass.ui.Application.checkEventThread(Application.java:445)
14:13:35 - [Typer][ERROR]:      com.sun.glass.ui.Robot.keyPress(Robot.java:68)
14:13:35 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.doType(FXKeyboard.java:590)
14:13:35 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.doType(FXKeyboard.java:577)
14:13:35 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.type(FXKeyboard.java:190)
14:13:35 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.typeFile(FXKeyboard.java:461)
14:13:35 - [Typer][ERROR]:      com.mattc.autotyper.gui.fx.FXAutotyperWindow$5$2.run(FXAutotyperWindow.java:254)
14:13:35 - [Typer][ERROR]:      java.lang.Thread.run(Thread.java:745)
14:13:35 - [Typer][ERROR]: ===============EXCEPTION===============
14:13:45 - [FX_GUI][INFO ]: Downloading AWbyyx5E from http://www.pastebin.com/raw.php?i=AWbyyx5E...
14:13:45 - [FX_GUI][INFO ]: Finished!
14:13:59 - [Typer][INFO ]: Writing File of Size 15 KB consisting of 519 lines
14:13:59 - [Typer][ERROR]: ===============EXCEPTION===============
14:13:59 - [Typer][ERROR]: Exception of type java.lang.IllegalStateException caught!
14:13:59 - [Typer][ERROR]: Error Message: This operation is permitted on the event thread only; currentThread = Typer
14:13:59 - [Typer][ERROR]: Caught by UncaughtExceptionHandler
14:13:59 - [Typer][ERROR]: =======================================
14:13:59 - [Typer][ERROR]: Stack Trace: 
14:13:59 - [Typer][ERROR]:    com.sun.glass.ui.Application.checkEventThread(Application.java:445)
14:13:59 - [Typer][ERROR]:      com.sun.glass.ui.Robot.keyPress(Robot.java:68)
14:13:59 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.doType(FXKeyboard.java:590)
14:13:59 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.doType(FXKeyboard.java:577)
14:13:59 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.type(FXKeyboard.java:190)
14:13:59 - [Typer][ERROR]:      com.mattc.autotyper.robot.FXKeyboard.typeFile(FXKeyboard.java:461)
14:13:59 - [Typer][ERROR]:      com.mattc.autotyper.gui.fx.FXAutotyperWindow$5$2.run(FXAutotyperWindow.java:254)
14:13:59 - [Typer][ERROR]:      java.lang.Thread.run(Thread.java:745)
14:13:59 - [Typer][ERROR]: ===============EXCEPTION===============

**Comment by glossawy** [comment]
That is just... silly. I was so focused on getting the GUI to work properly and auto-completion and making the code look better and be more maintainable that I forgot to make the do/do not button do something and to fix that fatal bug. 

Thanks.

**Comment by glossawy** [comment]
Fixed. Release v2.0a updated (Not Significant Enough to Warrant a new update)
